language: node_js
node_js:
  - "10"
  - "12"

cache:
  directories:
    - node_modules
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash

script:
  - yarn test

after_success: yarn run coverage
